apiVersion: v1
kind: Service
metadata:
  name: go-masters
  namespace: go-masters
  labels:
    app: go-masters
spec:
  type: ClusterIP
  selector:
    app: go-masters
  ports:
    - port: 80
      targetPort: 8080
